quarkus:
  datasource:
    db-kind: mariadb
    username: coh_dev
    password: coh_dev_password
    jdbc:
      url: jdbc:mariadb://localhost:3306/coh_dev
  oidc:
    auth-server-url: http://localhost:8080/realms/quarkus
    client-id: my-client
    credentials:
      secret: my-secret
  smallrye-openapi:
    info:
      title: Clair Obscur API
      version: 1.0.0
